language: node_js
node_js:
- '4.1'
before_install:
- npm install -g tsd
deploy:
  provider: npm
  email: npm@smart-coordination.com
  api_key:
    secure: xddxOevdpnc4OZoJygJQiERFSXDOA3YUJ7SH7+OjY9/RaneW7k1dyIju+A5OlW+rjGlBkNRagLlMXF0+lri60SFT68Sb56Q5BxecIatIPgZNB0i9krO9Ly92fQFpBPXZcu6Ss3prv79ESQAXugjK8dW/BRnBsTsYTN4ixdb2TEqA+olODp84TYwc0ogTeKgdywEcEvR3LzFwE/UccUvszInKpauc4kmrxZk3Qks6CJQ69gTPsQorNY+oa/3TYGnMGtj0Zfmi4EhaW/kmC/zMdNQeDhA3pA5qdSIKHjWAdErcXejwZCiuJ3fibdoVKtfN1sCQNzeIPfEcAATr85KAUFMzE7el3GgFseJZ9T1f3EcwiwPTwjqV20yYKNvyNtydkjuHkKEqx1SxUU+WG6ck4h/7zdzqXZmU7hgfYTPT/CE1uagI1gNEbRg6QTwZItTm8QT71l2B8t4YK5klfW6+2+h12X1MILbmzNncJKq2b5wtJloXjMY6cTPwCImlXrRz+wieSUy3tNfn7MM+Cx8EkYfLl2JoE5G5BX0ALAF0v8cNAh/bIJ28u8HQwRswHgvMeLsD4YJS3P4FhuIxjxU2E/DbzRCAVQ+clH03OPV2acgRiU9fLnPnZ/IZQxYF0/6bbNteVsuxITeLNbcEXt0vuF51BWU+8T/Hq83wXZaj13A=
  on:
    tags: true
    repo: pushrocks/smartgit
notifications:
  slack:
    secure: f5Uss0z9RPl/QcA/DroB8loyE93aOYI6bqCkrsiUscmZtlv/TVQtT4dxqGA6uvcG6iTQDBi3Ul88dQxWkRm4IqbhY35/iMaV2dHW4FVYMAh8GQMbsfL2sALCcufxD9blw47awv3iFcwhV1EeyesscjgL0JIjduk96v/7G/6QIO2838M1lzlgtj+kRUkim8qkaEs1je3gRrhMUIjLuAdscMXyUKYFMjWo9ACSjVUl30R/ZNemb18itIja6i92GotreBgcfEMczvy58ovDC7xdJUsY8LjMI01DwY+WPRnI0tAhsuI8moBwwcdM4e3bAjKjucQRjO33O5bMWRZ6QCiYd0DnCEFyCPQLJ4GSy/tkD00n8ijLHAOSV3AH1zNbdK1EAdSPQXDvlI36KJn/2hyQLoitGHVUPr76ujJWP82ypO2tgIp3XQU0dJVCxDuHnwJO2+hjdI+gCPqxNTpjeujHx3UdkTGNRjuuf9dlZ/D08fApjYxy2fxItTqo3QjP/nrqvBXUOPP8yPHpjIT4H2t5Pr4SJjBGI6X4qhKyFj6s9rA/Xu1rL+45zu1C3uC3z+u3T9UwrbzJ/cZM6r6UQvQmUvIfBNaMlg4I/diQCDIPL+Rhop2nylY3IcHmJnk2itn7kOqj1tohCpFEml5pRuSZy4udWywkdtyBAsHWFLF7oiQ=
